# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('faculty_name', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id1', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id1', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('reg_done', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=1)),
                ('mess_dues', models.IntegerField(default=0)),
                ('mess_fees', models.IntegerField(default=0)),
                ('lib_dues', models.IntegerField(default=0)),
                ('reg_fees', models.IntegerField(default=0)),
            ],
        ),
    ]
