# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch_mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('mentors', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='compulsary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('faculty_code', models.CharField(max_length=10, null=True)),
                ('faculty_name', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id1', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(blank=True, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='fulldetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('id1', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=30)),
                ('reg_done', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=1)),
                ('branch', models.CharField(max_length=30, null=True)),
                ('mess_dues', models.IntegerField(default=0)),
                ('mess_fees', models.IntegerField(default=0)),
                ('lib_dues', models.IntegerField(default=0)),
                ('reg_fees', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='fulldetails',
            field=models.ManyToManyField(blank=True, to='app.fulldetail'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='requests',
            field=models.ManyToManyField(blank=True, to='app.request'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, to='app.student'),
        ),
        migrations.AddField(
            model_name='compulsary',
            name='sem1',
            field=models.ManyToManyField(blank=True, related_name='sem1', to='app.course'),
        ),
        migrations.AddField(
            model_name='compulsary',
            name='sem2',
            field=models.ManyToManyField(blank=True, related_name='sem2', to='app.course'),
        ),
        migrations.AddField(
            model_name='compulsary',
            name='sem3',
            field=models.ManyToManyField(blank=True, related_name='sem3', to='app.course'),
        ),
        migrations.AddField(
            model_name='compulsary',
            name='sem4',
            field=models.ManyToManyField(blank=True, related_name='sem4', to='app.course'),
        ),
        migrations.AddField(
            model_name='compulsary',
            name='sem5',
            field=models.ManyToManyField(blank=True, related_name='sem5', to='app.course'),
        ),
        migrations.AddField(
            model_name='compulsary',
            name='sem6',
            field=models.ManyToManyField(blank=True, related_name='sem6', to='app.course'),
        ),
        migrations.AddField(
            model_name='compulsary',
            name='sem7',
            field=models.ManyToManyField(blank=True, related_name='sem7', to='app.course'),
        ),
        migrations.AddField(
            model_name='compulsary',
            name='sem8',
            field=models.ManyToManyField(blank=True, related_name='sem8', to='app.course'),
        ),
    ]
