# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='request1',
        ),
    ]
