# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160306_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
