# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='mentor',
            field=models.BooleanField(default=False),
        ),
    ]
