# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_faculty_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='request1',
            name='branch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='request1',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request1',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request1',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
