# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160306_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_mentor',
            name='mentors',
        ),
        migrations.AddField(
            model_name='branch_mentor',
            name='sem1',
            field=models.ManyToManyField(blank=True, related_name='sem1', to='app.faculty'),
        ),
        migrations.AddField(
            model_name='branch_mentor',
            name='sem2',
            field=models.ManyToManyField(blank=True, related_name='sem2', to='app.faculty'),
        ),
        migrations.AddField(
            model_name='branch_mentor',
            name='sem3',
            field=models.ManyToManyField(blank=True, related_name='sem3', to='app.faculty'),
        ),
        migrations.AddField(
            model_name='branch_mentor',
            name='sem4',
            field=models.ManyToManyField(blank=True, related_name='sem4', to='app.faculty'),
        ),
        migrations.AddField(
            model_name='branch_mentor',
            name='sem5',
            field=models.ManyToManyField(blank=True, related_name='sem5', to='app.faculty'),
        ),
        migrations.AddField(
            model_name='branch_mentor',
            name='sem6',
            field=models.ManyToManyField(blank=True, related_name='sem6', to='app.faculty'),
        ),
        migrations.AddField(
            model_name='branch_mentor',
            name='sem7',
            field=models.ManyToManyField(blank=True, related_name='sem7', to='app.faculty'),
        ),
        migrations.AddField(
            model_name='branch_mentor',
            name='sem8',
            field=models.ManyToManyField(blank=True, related_name='sem8', to='app.faculty'),
        ),
    ]
