# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
