# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_message_sname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ltp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
