# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_course_ltp'),
    ]

    operations = [
        migrations.AddField(
            model_name='request1',
            name='ctype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
