# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_request1_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_fulldetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id1', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, to='app.course')),
            ],
        ),
    ]
