# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_final_fulldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulldetail',
            name='branch',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fulldetail',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fulldetail',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
