# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20160307_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll', models.CharField(max_length=30)),
                ('typefees', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course Code. \nExample : CS221', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='ltp',
            field=models.CharField(help_text='Enter in the form L-T-P [credit]     Example: 3-0-3 [4]\n', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='request1',
            name='semester',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('cse', 'Computer Science & Engineering'), ('ele', 'Electrical Engineering'), ('mech', 'Mechanical Engineering')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id1',
            field=models.CharField(help_text='This is LDAP id', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='lib_dues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='mess_dues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='mess_fees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(help_text='This is LDAP password', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_done',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='reg_fees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.PositiveIntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')], default='1st'),
        ),
    ]
