# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20160411_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='cardno',
            field=models.BigIntegerField(default=0),
        ),
    ]
